### ISSUE TITLE
The code has some error

### ISSUE THREAD

**Issue by Hekopyooo** [godotengine/tps-demo#105]
when i import the file into godot engine and wanted to run it, then in the player.gd it says expected "or"
so... is it a bug? or something because when i watched someone in youtube he can play without any error

**Comment by aaronfranke** [comment]
Please provide more details. What are your system specs? Where in the player.gd file does it say there's an error? Can you take a screenshot of it?

**Comment by Hekopyooo** [comment]
here it is
