### ISSUE TITLE
Compression on .blend files

### ISSUE THREAD

**Issue by NewNodeGames** [godotengine/tps-demo#11]
For reduce the size of the project Blender have an option to compress the .blend file. Player.blend is reduced from 25.2 MB to only 4.9 for example.
Steps to follow:
1- Open the .blend file on Blender.
2- Go to File and select Save as.
3- In the left options menu set "Compress" to true.
This can also be changed in preferences.

**Comment by FeralBytes** [comment]
But the compression would also require godot to decompress the files right? If so then that could hurt performance.
