### ISSUE TITLE
Error opening version 3.4-4a9d4f3

### ISSUE THREAD

**Issue by JA-Developer** [godotengine/tps-demo#114]
**OS/device including version:**

Windows 10 Home, 64 bits, AMD Radeon R5 Graphics

**Issue description:**

Hello,

Today, I just downloaded the TPS demo (Version 3.4-4a9d4f3) from this repository. I am trying to open it with Godot Engine 3.4 x64 stable (standard version) but I am getting these errors:

> ERROR: Cannot open file 'res://.import/door.dae-7f8548364364a8c72d317db0aac6a97d.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/open_close.wav-15c93b82a463a1fe63bbc03e48e48393.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/BlastMesh.glb-b73267f06de3a944c01538e9fdef2594.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/charge.wav-ca59df8cae0ad5b1fea987f205ca4e33.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/explosion.wav-8b1408a92e13f73affdc0326a2858c09.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/hit.wav-0382ddf0ec7020fb04e2666fb8b2f72f.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/shoot.wav-81aef4aff359235fd45078daadcb9e5e.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/walk.wav-9036336121ed9699b9a0fe895306c86a.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/LightRaysMesh.glb-7064e2802466cd2578058f8b016cbc85.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/BarrelSmoke.glb-8e2d69c4951af8065240d2d52c721128.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/red_robot.dae-1b7c21e895639cdfc51b4632e66bc08e.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/SparkParticle.glb-e3f6706407f31f2c4028af0147be98dc.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/part_head.glb-8de207327aec4b1572370054a7354cf7.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/part_shield.glb-d6c233d3d85ae961b022dca28194d5a7.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/ray.glb-8e1d5bd28d6e0c01a107a5b661f05121.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/flying_forklift.glb-5fc3f6403d54a193b6e3b14c2633d073.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/core.glb-6d1fe901749789ad3144bf80da386b2d.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/lights.glb-e682766b019cdb9ecca59a07b4749bef.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/props.glb-ef7d7320b04a8755385d61edb896d714.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/structure.glb-21fe3543c920768091702bd640720751.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/level_music.ogg-4afd12677c88b2d2a03f7bd78697bf1a.oggstr'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/menu_intro_music.ogg-790ed16894e4b5a52d74fb71b5f5de88.oggstr'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/jump.wav-2603877681c9e067c3a9a93e9a4fc8fc.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/land.wav-30873fe661744bdc60c0d00d7401aab3.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/shoot.wav-8244db64ae3703b75575788340a3a2e5.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/step.wav-d0eb4ea2bd4432739110520bfa71a096.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/bullet_explode.wav-cb1cff5a50e4c409ec7fc505de7bc81f.sample'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/muzzle_flash_particle_mesh.glb-a66d023aa0694204914831451c14f128.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> ERROR: Cannot open file 'res://.import/player.glb-4fab3988dc7fd5b74f5ba5057da16803.scn'.
>    at: (core/io/resource_format_binary.cpp:984)
> WARNING: Ignoring unsupported header information in HDR: GAMMA=1.
>      at: load_image (modules/hdr/image_loader_hdr.cpp:50)
> WARNING: Ignoring unsupported header information in HDR: PRIMARIES=0 0 0 0 0 0 0 0.
>      at: load_image (modules/hdr/image_loader_hdr.cpp:50)
> WARNING: Octahedral compression cannot be used to compress a zero-length vector, please use normalized normal values or disable octahedral compression
>      at: norm_to_oct (servers/visual_server.cpp:341)
> ERROR: Resource file not found: res://door/model/doorsimple_d.png.
>    at: (core/io/resource_loader.cpp:275)
> ERROR: Resource file not found: res://enemies/red_robot/model/EvilRobo-BaseColor.png.
>    at: (core/io/resource_loader.cpp:275)

And the folder is in the path: C:\Users\JASP\Downloads\tps-demo-3.4-4a9d4f3

I don't know what I'm doing wrong, please help me q_q. 

**Screenshots of issue:**

These are the files in my project folder:

![image](https://user-images.githubusercontent.com/40817962/140699213-dff5543b-8521-49e6-9092-72170ae9ece5.png)

This is the error I get:

![image](https://user-images.githubusercontent.com/40817962/140699565-30256dd0-4470-451f-af70-34d1b06822eb.png)

**Comment by akien-mga** [comment]
At least some of those errors are normal when you edit the project for the first time, as the resources haven't been imported yet to the `.import` folder. They should disappear on second run, can you confirm?

**Comment by JA-Developer** [comment]
Oh yeah. They disappeared. I thought it was a bug.

Thank you very much for the quick response, hehe

**Comment by akien-mga** [comment]
Closing then, it's a general UX issue with Godot not specific to this project.
