### ISSUE TITLE
Touchpads cannot left-click shoot while holding right-click to aim

### ISSUE THREAD

**Issue by pjhanzlik** [godotengine/tps-demo#116]
Love the demo, but could not shoot on my laptop because the action is mapped to one-finger tapping my touchpad while aiming.  Aiming requires two fingers held on the touchpad, so adding an additional finger to shoot is actually a three-point touch (which is unmapped).

**Comment by Calinou** [comment]
I suppose this can be fixed by aiming making a toggle instead of requiring holding. If we wish to preserve the "hold" behavior, we can make it so tapping briefly enters toggle mode, whereas holding for a duration longer than 0.5 seconds enters "hold" mode.

**Comment by pjhanzlik** [comment]
Entering hold mode based on duration sounds cool.  I would also like to try using `get_action_strength` where 1 indicates toggle aim, and less than 1 indicates holding aim. (I suppose at this point both methods would be called threshold aiming?)

**Comment by aaronfranke** [comment]
@pjhanzlik That method won't help, mouse clicks are boolean inputs. The proposed behavior will need custom code.

**Comment by akien-mga** [comment]
Wouldn't it be simpler to add dedicated controls for keyboard + touchpad?

Like a specific key to toggle aim mode, and another key to shoot. Touchpad should only be used to aim, not to trigger precise actions like mouse buttons would IMO.

**Comment by Calinou** [comment]
> Like a specific key to toggle aim mode, and another key to shoot.

Shooting by pressing a key is very uncommon in FPS/TPS games. I think using a touchpad for a FPS/TPS game will never be an ideal solution, so we should just try to make it work the best way we can without affecting mouse users negatively.
