### ISSUE TITLE
Not a bug or an enhancement, but a violation of the LICENSE

### ISSUE THREAD

**Issue by xsellier** [godotengine/tps-demo#119]
Hey,

Sorry to bother you with this, but someone stole your work and started selling it on itch:
https://epic-virtual-boost.itch.io/space-x-robo-game

Bests.

**Comment by Calinou** [comment]
The [license](https://github.com/godotengine/tps-demo/blob/master/LICENSE.md) does not disallow selling (un)modified versions of the TPS demo, so we cannot do anything about it (other than make a forum post about it).

**Comment by xsellier** [comment]
Since it is a CC0, they should at least mention you right?

**Comment by aaronfranke** [comment]
The files of this repository are either CC-BY or MIT, so they legally do need to include credit and a copy of the MIT license.

**Comment by Legionisgod** [comment]
ihave removed it

**Comment by Legionisgod** [comment]
removed this game sorry
