### ISSUE TITLE
Add mobile controls

### ISSUE THREAD

**Issue by ghost** [godotengine/tps-demo#121]
Hey i can compile the game for Android but can team Godot help me to add mobile control in it i can not do that

**Comment by Calinou** [comment]
Considering the demo has high-end hardware requirements, it currently doesn't run well on mobile. Therefore, adding mobile controls is low-priority.

**Comment by Legionisgod** [comment]
Do you think your mobile can handle it. For eg like GtaV cannot be runned on mobile Cuz it is high end game + Pretty Resources demanding Similarly here

**Comment by dukelanovic** [comment]
The game you made really sucks - my nephew mainly plays Roblox and somehow, he also was deeply impressed as he saw your game. - I am an engineer of electronics - in pension right now... So, I have a plenty of time to help you implementing stuff over electronics. - Pavle

**Comment by dukelanovic** [comment]
Hey Shalom Aaron - Friede sei mit Dir. Thank you for your software - it is very powerful and I really was deeply impressed by it. - Pavle

**Comment by dukelanovic** [comment]
Shalom and peace be upon you Aaron,
I hope things will be better next days.
Pavle
   Am Montag, 3. Juli 2023 um 17:12:10 MESZ hat Aaron Franke ***@***.***> Folgendes geschrieben:  
 
 


Closed #121 as not planned.
