### ISSUE TITLE
Where is the font for the main menu ?

### ISSUE THREAD

**Issue by Nutriz** [godotengine/tps-demo#13]
I wanted to add a "Quit" button to the menu but the font used for the existing buttons and the the title is not present in the project. There is a font folder with a ttf file and a `button_font.res` in the project, but it's not the right font, apparently the font used in settings menu.

By the way, TextureButton isn't the best choice for a community project, difficult to add new button, must generate images with right size and also have the blur used for the hover effect. 
If someone can add the right font I can try to add Buttons with the font and find a way to get the blur effect with shader.

**Comment by Nutriz** [comment]
Maybe @reduz can answer this ? :blush:

**Comment by akien-mga** [comment]
It's FreeMono Bold. I'm adding a Quit button now.

**Comment by Nutriz** [comment]
Thanks for that.
