### ISSUE TITLE
Neon light-emissive materials flicker depending upon angle and distance

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/tps-demo#143]
**OS/device including version:**
Linux 5.15.0 64-Bit (Ubuntu 22.04), NVidia 1650Ti (using NVidia drivers).

Using Godot v3.5.stable.official [991bb6ac7], most recent pull of the TPS demo repository.

**Issue description:**
Depending on the distance and angle, some of the lighting will flicker/distort when it should not.

https://www.dropbox.com/s/sf0h8ks27ake4yw/143_demonstrator.webm?dl=0 shows the issue in action.

**Comment by Calinou** [comment]
I can confirm this on 3.5 (Linux, NVIDIA 515.57).

**Comment by Sslaxx** [comment]
@Calinou - Can't get it to work with Beta 1. It's glitchy in Betas 2 to 5.
