### ISSUE TITLE
Recommendation to run the project converter

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/tps-demo#164]
Since the latest godot RC is out I recommend running the 3 to 4 project converter at least once on this as I have made a fix upstream for a node ownership issue which this repository has present.

It should resolve a crash I found when running the game.

**Comment by RevoluPowered** [comment]
https://github.com/godotengine/godot/pull/73725

**Comment by clayjohn** [comment]
We already have a 4.0 port mostly done, so its a bit late to run the converter again. In my local branch I went a ahead and did the renames manually. Will make a PR soon

**Comment by RevoluPowered** [comment]
nice!

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/tps-demo/pull/166.
