### ISSUE TITLE
Distribution of game

### ISSUE THREAD

**Issue by SuperuserLinux** [godotengine/tps-demo#173]
Hi there We are making a Linux distro we need your game like we will compile it and publish it for free so we can make a thing like xbox we will give you full credit of it. So what do you think And your license also says we can redistribute it

**Comment by aaronfranke** [comment]
Yes, you can redistribute it as long as credit is given by including a copy of the license including copyright statement.

**Comment by Calinou** [comment]
Closing per the above comment. Note that this is not a full game, but a tech demo.
