### ISSUE TITLE
TPS demo display incorrect (Third-Person Shooter Demo)

### ISSUE THREAD

**Issue by njikmf** [godotengine/tps-demo#175]
**OS/device including version:**
 Windows10

**Issue description:**

You see there are two  "weired circle " ... I don't know how to describe them... I tried different options but the two "circles" always here.

**Screenshots of issue:**

Hi, I'm learning Godot , I downloaded the TPS demo and opened it with latest Godot 4.1.2 but I found it's weired.
![Capture](https://github.com/godotengine/tps-demo/assets/96371060/c9004898-1c80-44b4-9347-5f4fba1f0c61)

You see there are two  "weired circle " ... I don't know how to describe them... I tried different options but the two "circles" always here.
Anybody can tell me why or how to solve this ?

**Comment by QbieShay** [comment]
Hey! This is a godot bug and is tracked here: https://github.com/godotengine/godot/issues/81772

Please follow the issue there since the proper fix has to come  in the engine.
