### ISSUE TITLE
missing dependencies - player.dae

### ISSUE THREAD

**Issue by chiboreache** [godotengine/tps-demo#18]
Hi there! I have an error, can help someone?

![image](https://user-images.githubusercontent.com/16459251/48537952-282be700-e8c4-11e8-9bbc-5386d2be46df.png)

**Comment by akien-mga** [comment]
You need to use Git LFS to fetch it: https://github.com/godotengine/tps-demo#git-lfs

**Comment by chiboreache** [comment]
yeah, I read about it =)

![image](https://user-images.githubusercontent.com/16459251/48539321-d38a6b00-e8c7-11e8-96d2-29e863786843.png)

**Comment by akien-mga** [comment]
Did you run `git lfs install` after installing the package?
And then you need to run this in your Godot clone:
```
git lfs fetch
git checkout master
```
(as documented in the README)

**Comment by chiboreache** [comment]
Nope. But yeah I already realize it, I just need to repeat twice, thanks -_-
