### ISSUE TITLE
Graphic looks different on my machine

### ISSUE THREAD

**Issue by njikmf** [godotengine/tps-demo#182]
**OS/device including version:**

Win10, GTX1660

**Issue description:**

Godot 4.2 steam version

I tried the three option (Lightmap, Voxel, SDFGI), but only the Lightmap looks similar to your official effect, I mean the screenshot on the steam page and here https://github.com/godotengine/tps-demo/blob/master/screenshots/screenshot.png

For details, these three option looks too light or too dark,  the yellow sphere missing some "Particle effect" ? I'm not sure.. and so on.

Anything need me to setup or is this worked as designed?

**Screenshots of issue:**

Lightmap
![lightmap](https://github.com/godotengine/tps-demo/assets/96371060/ac80b3ed-98d0-4335-88bd-2bdd6519767b)

Voxel
![voxel](https://github.com/godotengine/tps-demo/assets/96371060/00fd79c8-e9c8-4416-9631-cd1c3cd9bc72)

SDFGI
![sdfgi](https://github.com/godotengine/tps-demo/assets/96371060/e995a2f3-0654-4113-8ce4-4c0337ad992d)

**Comment by Calinou** [comment]
The version you're using seems to be outdated. Please use the latest `master` branch from this repository (https://github.com/godotengine/tps-demo/commit/241b450ed64edc9023546c4f47bae3e137ed28f6 as of writing).

In particular, **Multiplayer ID** shouldn't appear on the HUD if **Online** is **false**.

**Comment by njikmf** [comment]
Thanks !
I have changed the 4.0 branch to master and it looks great!!!
