### ISSUE TITLE
Please tutorial particulas with godot------¨Por favor tutorial de particulas con godot engine.

### ISSUE THREAD

**Issue by kone9** [godotengine/tps-demo#19]
Definitivamente quiero una serie de tutoriales sobre particulas con godot engine.Gracias por compartir el proyecto,es un gran aporte a la comunidad que apostamos por este motor.

Definitely I want a series of tutorials about particles with godot engine. Thanks for sharing the project, it is a great contribution to the community that we bet on this engine.

**Comment by akien-mga** [comment]
This is not the place to request tutorials, that would be https://github.com/godotengine/godot-docs
