### ISSUE TITLE
Disappearing arms and legs when running

### ISSUE THREAD

**Issue by Silvea12** [godotengine/tps-demo#20]
These have been seen on a GTX 660 as well as an RX Vega M. Tested on both windows and linux, with both latest build on hugo.pro as well as beta 3:
A: Missing left arm padding for player
B: Missing left leg padding for enemies
C: Particle effects are not visible for orb

A + B:
![peek 2019-02-04 22-40](https://user-images.githubusercontent.com/3120639/52206406-3b03f580-28ce-11e9-8d33-e66f17dbef6c.gif)

C:
![peek 2019-02-04 22-41](https://user-images.githubusercontent.com/3120639/52206418-435c3080-28ce-11e9-853f-02d34e6ffcca.gif)

**Comment by akien-mga** [comment]
Confirmed at FOSDEM and GodotCon.
It's a regression, so it would be great if someone can test earlier
releases and check which one broke it.

**Comment by Silvea12** [comment]
Is this a regression of the engine or the project?

-------- Original Message --------

**Comment by akien-mga** [comment]
In the engine I think, the project hasn't changed recently.

**Comment by Silvea12** [comment]
Do we have a version/hash/time that we know it was working? I can try to cherry pick it this weekend.

-------- Original Message --------

**Comment by akien-mga** [comment]
> Do we have a version/hash/time that we know it was working? I can try to cherry pick it this weekend.

Well that's what I was mentioning above, someone should go to https://downloads.tuxfamily.org/godotengine/3.1/ and download binaries of recent dev snapshots to narrow it down. I guess it must have been working around alpha2 (November), as that's around when the demo was finished (October).

**Comment by butterflyeight** [comment]
i5-8300h/GTX 1050, can report the same issue with beta 4, plus the absence of explosion effect when killing the robots. attempting testing of the older builds right now.

**Comment by butterflyeight** [comment]
the issue goes to as far as alpha5. i also get problems related to #1, is it related to that? 

![alpha5](https://user-images.githubusercontent.com/47599466/52715440-2813b400-2fa5-11e9-81c3-c1e9500948a2.png)

**Comment by butterflyeight** [comment]
alpha 4, same issues, except i went to check up the orb and the particle effects actually work there
![image](https://user-images.githubusercontent.com/47599466/52716270-16331080-2fa7-11e9-91b4-3dbbdfc319b0.png)

**Comment by butterflyeight** [comment]
tested alpha 2 and 3, and now i can confirm that regressions A and B are present in the latter version. another thing of note is that weapon projectile particles are much larger in alpha 3 than they should be (in alpha 2). alpha 2 also runs much worse on intel hd, so i had to switch to 1050 for the rest of the tests, but it works correctly with integrated graphics as well. checking out the regression C now.

**Comment by butterflyeight** [comment]
given that i am already investigating into this issue, i might just find the commits that break the demo and open the issue in the main repo.

**Comment by butterflyeight** [comment]
okay, so i found the commit that broke the explosion and weapon projectile particles, it's https://github.com/godotengine/godot/commit/4ede92bdc80ac21c123f2b52a41bda2b56bd7fdf

the situation with disappearing arms is a bit murky and the initial bisect didn't point me at the build. after further testing, though, i found out that the demo imported to alpha2 build shows the limbs correctly in all the other builds. here's the comparison in beta4 of the demo imported to alpha2:
![image](https://user-images.githubusercontent.com/47599466/52819019-ecfea700-30b0-11e9-81d7-7c5e8538a8e9.png)
and the alpha3
![image](https://user-images.githubusercontent.com/47599466/52819740-c80b3380-30b2-11e9-8159-95bf6958038b.png)


@akien-mga should i open the issue in the main repo for this? this might be an either/or case but i am not too experienced to tell that.

**Comment by butterflyeight** [comment]
as of rc1 the disappearing limbs issue seems to be resolved. that checks all the boxes present in the op
![image](https://user-images.githubusercontent.com/47599466/54085490-68b5e180-4347-11e9-853f-67b512dabee1.png)

**Comment by akien-mga** [comment]
Thanks for the debugging, it was helpful to fix the issue! A fix was made shortly before the 3.1-stable release, so this can be closed.
