### ISSUE TITLE
Lightmap generation failures on first import

### ISSUE THREAD

**Issue by akien-mga** [godotengine/tps-demo#23]
When importing the TPS demo for the first time (`import/` deleted), I get those errors on godotengine/godot@36de6c1e:

![screenshot_20190227_145818](https://user-images.githubusercontent.com/4701338/53495366-1ef40e00-3aa0-11e9-803a-c75152f354cd.png)

**Comment by Calinou** [comment]
I can confirm those errors when importing the demo with Godot Git https://github.com/godotengine/godot/commit/255ea11502dd91a91d98e6d1bd054ceaf3aee619.

Restarting the editor makes the demo open without any errors.

**Comment by aaronfranke** [comment]
There doesn't appear to be any obvious reason why this exists. I think I'll try and refactor the demo to have GLB files instead of DAE collada files, perhaps we can even split up the model and ditch LFS?
