### ISSUE TITLE
Unable to load level.tscn with Godot official 3.1 version

### ISSUE THREAD

**Issue by thecocce** [godotengine/tps-demo#26]
At: scene/resources/resource_format_text.cpp:440
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208
ERROR: Failed loading resource: res://level/level.tscn
   At: core/io/resource_loader.cpp:285
ERROR: load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:996
ERROR: Failed loading resource: res://.import/demolevel.dae-8f363302f37767653f5d7ca6e6ed7cd8.scn
   At: core/io/resource_loader.cpp:285
ERROR: Failed loading resource: res://level/geometry/demolevel.dae
   At: core/io/resource_loader.cpp:285
ERROR: poll: res://level/level.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://level/geometry/demolevel.dae

**Comment by Akira1San** [comment]
Hmm i can load it. I used the git desktop app.
Does that mean the "demolevel.dae" is not downloaded correctly?

**Comment by Rycerzyk** [comment]
If you downloaded project as zip file from Github page, be aware that this method does not support files stored in Git LFS. So you need to clone repository manually (don't forget installing Git LFS extension, as stated in README).

**Comment by PucklaMotzer09** [comment]
After installing Git LFS you have to execute "git lfs pull" to download all missing files

**Comment by aaronfranke** [comment]
@thecocce If you are still having issues, please ensure you have all files downloaded. You can download full releases here: https://github.com/godotengine/tps-demo/releases

@Akira1San While I see that it worked for you, the GitHub desktop app is a very poor Git client. Consider instead using GitKraken, or Git on the command line.
