### ISSUE TITLE
Out of memory on first opening

### ISSUE THREAD

**Issue by Nutriz** [godotengine/tps-demo#3]
During the first opening of the project, RAM 100% full, PC crash. After 2 reboot, all asset where imported.

Well, I have 16go of RAM but it is not enough to importing assets :thinking:.

**Comment by reduz** [comment]
There is clearly a leak, indeed

**Comment by DevMagicLord** [comment]
Godot was stuck building lightmaps when opening the project the first time.
I just wanted to open the project remove the lightmapper and use gi probe only.

Can Godot get an option to tell to not build lightmaps when opening a project ?

**Comment by DevMagicLord** [comment]
Some things i found : 

1) Walking robots turrets does not rotate up and down, they always fire horizontally.

2) When player shoots robots from long distance, robots take damage but continue ignore the player.
Small improvment : when robot take a hit make it aware of the player during some seconds whatever is the distance.

**Comment by akien-mga** [comment]
@DevMagicLord Please open other issues for that.

**Comment by aaronfranke** [comment]
@Nutriz Are you still experiencing this issue with Godot 3.1.2 and the latest version of the demo?

**Comment by Nutriz** [comment]
@aaronfranke tested with 3.2 RC2 and the issue seems to be fixed.

**Comment by QbieShay** [comment]
Tested on latest master and I can't reproduce either (Linux)
