### ISSUE TITLE
Falling through world

### ISSUE THREAD

**Issue by menip** [godotengine/tps-demo#32]
Easy to jump over railings and fall forever. Additionally, if you approach orange blocks from where red robot is, they will cause you to have vertical momentum, basically assuring you will fall over rail and into world.

**Comment by menip** [comment]
Note that seem to gain vertical momentum anytime approaching/colliding with orange block head on.

**Comment by aaronfranke** [comment]
I think the best solution would be to have a check that resets the player if they fall off. This way you wouldn't have to restart the demo project if you fall off the level.
