### ISSUE TITLE
git lfs fetch - Not in a git repository

### ISSUE THREAD

**Issue by zohozer** [godotengine/tps-demo#36]
Hi.

I just want to clone this project into a Windows10 machine, using the git in command-line and I get the following error message:

λ git lfs fetch
Not in a git repository.

I have no clue haw to fix this and I can't find any answer searching online.

**Comment by akien-mga** [comment]
You have to clone this repository first, and run `git lfs fetch` inside the repository's clone:
```
git clone https://github.com/godotengine/tps-demo
cd tps-demo
git lfs install
git lfs fetch
git checkout master
```

**Comment by zohozer** [comment]
Thank you. that did the trick
