### ISSUE TITLE
Cannot clone the repo due to  "repository over quota" error

### ISSUE THREAD

**Issue by JackLenz92** [godotengine/tps-demo#38]
I cloned the repo but it fails to checkout the lfs files. If i try a `git fts fetch`, this is the result:

`git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/godotengine/tps-demo.git/info/lfs'`

How can i solve this?
Thaanks

**Comment by waterdu** [comment]
I have the same problem

**Comment by frankiezafe** [comment]
same problem:
```
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/godotengine/tps-demo.git/info/lfs'
```

**Comment by hedgehog90** [comment]
Same issue.

**Comment by akien-mga** [comment]
No need to confirm the issue further, if we're over quota, it's the same for everyone.

**Comment by hedgehog90** [comment]
Any idea when it *won't* be over quota?

**Comment by akien-mga** [comment]
Next month: https://help.github.com/en/articles/about-storage-and-bandwidth-usage#bandwidth-quota

**Comment by akien-mga** [comment]
If anyone has an up to date local clone of this repo and can provide a tarball, I can upload it to GitHub Releases so that people can get the data without Git LFS.

**Comment by Calinou** [comment]
A release containing the repository + the LFS files has been uploaded on the [Releases page](https://github.com/godotengine/tps-demo/releases).

**Comment by aitorCerecetoGlovoApp** [comment]
> A release containing the repository + the LFS files has been uploaded on the [Releases page](https://github.com/godotengine/tps-demo/releases).

For some reason I cannot import the wav files, my OS it says they are empty (POP_Os 19.04).

**Comment by Calinou** [comment]
@aitorCerecetoGlovoApp Which Godot version are you using? Does it work if you use a [nightly build](https://hugo.pro/projects/godot-builds/)?

**Comment by aitorCerecetoGlovoApp** [comment]
@Calinou godot 3.1.1 stable x11 64. I'll try with nightly.

**Comment by aitorCerecetoGlovoApp** [comment]
Problem remains. The sound files themselves are empty for some reason

**Comment by aitorCerecetoGlovoApp** [comment]
Solved, it seems .7z file is corrupted. Everything fine with Source Code zip

**Comment by fedor-elizarov** [comment]
Broken for Godot Version 3.0.6
Fine     for Godot Version 3.2.x

**Comment by aitorCerecetoGlovoApp** [comment]
Error opening Player.dae 
![imagen](https://user-images.githubusercontent.com/40390402/62472552-406bcb00-b79f-11e9-9111-85734a59220e.png)

**Comment by unfa** [comment]
> Error opening Player.dae
> ![imagen](https://user-images.githubusercontent.com/40390402/62472552-406bcb00-b79f-11e9-9111-85734a59220e.png)

I have the same issue.
```
$ du -h player.dae
4,0K    player.dae
```
Looks like git-lfs didn't pull in all the files properly. Even though it doesn't raise any errors:

```
$ git lfs fetch
fetch: Fetching reference refs/heads/master
```

**Comment by Calinou** [comment]
@unfa You can use the [packaged release](https://github.com/godotengine/tps-demo/releases). Unfortunately, I'm not sure if the quota issue will be solved :slightly_frowning_face:
