### ISSUE TITLE
No proper download instructions

### ISSUE THREAD

**Issue by nezvers** [godotengine/tps-demo#39]
Good for you to know all the git commands, but not everyone is using git every day.
My git usage is limited to using GitHub Desktop to upload the repository and update it.
If people have to use git command lines to download this project then write instructions on commands letter by letter as it has to be written, not just faint hint for those who know-how.

**Comment by Xrayez** [comment]
It can be confusing indeed, have you looked into https://github.com/godotengine/tps-demo/releases?

**Comment by aaronfranke** [comment]
As of #63, the demo no longer uses Git LFS, so you can easily clone with just normal Git.

Also, I just did a release, you can download it from [the releases page](https://github.com/godotengine/tps-demo/releases/tag/3.2-99e4f80) or the [Godot Asset Library](https://godotengine.org/asset-library/asset/678).
