### ISSUE TITLE
Object was deleted while awaiting a callback

### ISSUE THREAD

**Issue by Zincr0** [godotengine/tps-demo#4]
Trying to save any change over the template causes a "Object was deleted while awaiting a callback" infinite message spam on the console and the editor gets a soft lock.

**Comment by Zincr0** [comment]
Anyway, this seems to be a reported godot bug: https://github.com/godotengine/godot/issues/21590

**Comment by aaronfranke** [comment]
This is most likely fixed, so I'll close this. Feel free to comment if you're still having issues.

**Comment by sicienss** [comment]
I just encountered this in v3.2 stable after trying to add a .wav file to my project. Now the editor spams the console with this message and softlocks whenever I open my project.

**Comment by aaronfranke** [comment]
This issue tracker is for the TPS demo. If you are experiencing this issue with your project, create a minimal reproduction project and post it to the main tracker.
