### ISSUE TITLE
Character controller collision bug -gets pushed around and stuck

### ISSUE THREAD

**Issue by Flavelius** [godotengine/tps-demo#69]
https://streamable.com/c77hjy
The spot is shown in the video. Just walking forward pushes it to the side and at a certain point, where according to the editor debug view nothing special is happening, it gets stuck, removing the ability to move and jump.

**Comment by aaronfranke** [comment]
I can tell by the overly-orange fog that you are not running the latest version of the demo. I recently did a rewrite of the entire demo and I can't reproduce either of the two bugs you posted.

Please re-test with the latest `master` version of this demo, and with Godot 3.2.2 rc2 or newer (which *has not yet been released*, so for now the only way to run the latest version of this demo is by [compiling your own version of the 3.2 branch](https://docs.godotengine.org/en/stable/development/compiling/index.html). 3.2.1 and 3.2.2 rc1 *will not work*).

**Comment by Flavelius** [comment]
Yes, i downloaded it from the releases tab as cloning didn't work (never completed, tried a few times (stopped at some percentage into lfs objects i think)). I'll have to wait until 3.2.2 releases officially then and retest.
