### ISSUE TITLE
Player x & z speed decreases when jumping

### ISSUE THREAD

**Issue by AceBreadman** [godotengine/tps-demo#78]
The player's x & z velocity suddenly decreases when running, after the jump key is pressed. 

Once the player returns to the ground, their x & z velocity is as normal.

I am unable to tell from the code, but is there some type of 3D velocity clamping that is causing the x & z velocities to decrease when the velocity.y is set to JUMP_SPEED on line 109?

**Comment by Calinou** [comment]
This is probably because jumping uses root motion, when it shouldn't.

**Comment by AceBreadman** [comment]
Which is the line that causes root motion? I will try and fix it.

**Comment by aaronfranke** [comment]
Fixed by #80
