### ISSUE TITLE
Name conflict when getting archive on Windows

### ISSUE THREAD

**Issue by Zylann** [godotengine/tps-demo#9]
One of the files in the demo exists twice with different casing. Which one is the right one? Could we remove the duplicate?

![image](https://user-images.githubusercontent.com/1311555/46671139-ea081d00-cbcb-11e8-932c-d631cfffdbe7.png)

**Comment by varkatope** [comment]
The error as it appears in the console:
0:00:06:0506   Case mismatch opening requested file 'Tile_Steel.material', stored as 'tile_steel.material' in the filesystem. This file will not open when exported to other case-sensitive platforms.
  <C Source>     drivers/windows/file_access_windows.cpp:104 @ _open()
  <Stack Trace>  menu.gd:98 @ _on_begin_load_timer_timeout()

**Comment by FrancoisSchnell** [comment]
4 months later, still no fix. Maybe someone can indicate in the readme that the demo is just for Linux/OSX.

**Comment by butterflyeight** [comment]
Faced the same issue while cloning via git. This doesn't seem to affect the demo overall.

**Comment by akien-mga** [comment]
I had a look but it's not clear to me which duplicate to remove, as both seem to be referenced in the `.dae`:
```
$ rg tile_steel
level/geometry/demolevel.dae
368:    <effect id="id-fx-32" name="tile_steel-fx">
2051:   <material id="id-material-36" name="tile_steel">

<snip>

$ rg Tile_Steel
level/geometry/demolevel.dae
29:     <image id="id-image-33" name="Tile_Steel_BaseColor.png">
30:             <init_from>../../../DemoLevel/Textures/Tile_Steel_BaseColor.png</init_from>
53:     <image id="id-image-145" name="Tile_Steel_Normal.png">
54:             <init_from>../../../DemoLevel/Textures/Tile_Steel_Normal.png</init_from>
963:    <effect id="id-fx-144" name="Tile_Steel-fx">
2093:   <material id="id-material-150" name="Tile_Steel">
```

The latter seems to reference textures which are not in the repo, so I guess it might be an older version. @reduz will check with the artist.
